W5D2/W5D2-projects/reddit_on_rails2/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subreddits do
    resources :posts
  end

  root to: "subreddits#index"

end

W5D2/W5D2-projects/reddit_on_rails2/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  has_many :post_subreddits,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :PostSubreddit,
    inverse_of: :post,
    dependent: :destroy

  has_many :subreddits, through: :post_subreddits, source: :subreddit

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

end

W5D2/W5D2-projects/reddit_on_rails2/app/models/post_subreddit.rb
class PostSubreddit < ApplicationRecord
  belongs_to :post,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :Post,
    inverse_of: :post_subreddits

  belongs_to :subreddit,
    primary_key: :id,
    foreign_key: :subreddit_id,
    class_name: :Subreddit,
    inverse_of: :post_subreddits
end

W5D2/W5D2-projects/reddit_on_rails2/app/models/subreddit.rb
class Subreddit < ApplicationRecord
  validates :title, :description, null: false
  validates :description, length: { minimum: 20 }

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :post_subreddits, inverse_of: :subreddit, dependent: :destroy
  has_many :posts, through: :post_subreddits, source: :post

end

W5D2/W5D2-projects/reddit_on_rails2/app/models/user.rb
class User < ApplicationRecord
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password
  after_initialize :ensure_session_token!

  has_many :subreddits,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Subreddit

  has_many :posts,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Post

  def ensure_session_token!
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def password=(pass)
    @pass = pass
    self.password_digest = BCrypt::Password.create(@pass)
  end

  def is_password?(pass)
    BCrypt::Password.new(self.password_digest).is_password?(pass)
  end

  def self.find_by_credentials(user, pass)
    user = User.find_by(username: user)
    return nil if user.nil?
    user.is_password?(pass) ? user : nil
  end
end

W5D2/W5D2-projects/reddit_on_rails2/app/controllers/application_controller.rb
require 'net/http'
require 'json'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :require_active_session
  helper_method :logged_in?
  helper_method :random_corgi_url

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_active_session
    unless logged_in?
      redirect_to new_session_url
    end
  end

  def random_corgi_url
    url = "https://api.giphy.com/v1/gifs/random?api_key=WowLIPJbsZymHSrRfupBUX9hdPH0AB13&tag=corgi&rating=R"
    resp = Net::HTTP.get_response(URI.parse(url))
    buffer = resp.body
    result = JSON.parse(buffer)
    result["data"]["image_original_url"]
  end

end

W5D2/W5D2-projects/reddit_on_rails2/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_active_session

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    @post.save
    flash[:errors] = @post.errors.full_messages
    redirect_to subreddit_url(@post.subreddits.first)
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])

    @post.update_attributes(post_params)
    flash[:errors] = @post.errors.full_messages
    redirect_to subreddit_url(@post.subreddits.first)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to subreddit_url(@post.subreddits.first)
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, subreddit_ids: [])
  end


end

W5D2/W5D2-projects/reddit_on_rails2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username],
                                    params[:user][:password])

    if @user.nil?
      flash.now[:errors] = ["Invalid username or password."]
      render :new
    else
      login!(@user)
      redirect_to user_url(@user)
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

W5D2/W5D2-projects/reddit_on_rails2/app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  before_action :require_active_session, except: [:index]

  def index
    @subreddits = Subreddit.all
    render :index
  end

  def new
    render :new
  end

  def create
    @subreddit = Subreddit.new(subreddit_params)
    @subreddit.moderator_id = current_user.id

    if @subreddit.save
      redirect_to subreddit_url(@subreddit)
    else
      flash.now[:errors] = @subreddit.errors.full_messages
      render :new
    end
  end

  def show
    @subreddit = Subreddit.find(params[:id])
    render :show
  end

  def edit
    @subreddit = Subreddit.find(params[:id])
    render :edit
  end

  def update
    @subreddit = Subreddit.find(params[:id])

    @subreddit.update_attributes(subreddit_params)
    flash[:errors] = @subreddit.errors.full_messages
    redirect_to subreddit_url(@subreddit)
  end

  def destroy
    @subreddit = Subreddit.find(params[:id])
    @subreddit.destroy
    redirect_to root_url
  end

  private
  def subreddit_params
    params.require(:subreddit).permit(:title, :description)
  end

end

W5D2/W5D2-projects/reddit_on_rails2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W5D2/W5D2-projects/reddit_on_rails2/app/helpers/posts_helper.rb
module PostsHelper
end

W5D2/W5D2-projects/reddit_on_rails2/app/helpers/subreddits_helper.rb
module SubredditsHelper
end

W5D2/W5D2-projects/reddit_on_rails2/app/views/posts/edit.html.erb
<% unless flash.now[:errors].nil? %>
  <% flash.now[:errors].each do |error| %>
    <h1 class="error-text"><%= error %></h1>
  <% end %>
<% end %>

<h1>Edit Post</h1>

<form class="sign-in-form" action="<%= subreddit_post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="title">Title</label>
  <input id="title" type="text" name="post[title]" value="<%= @post.title %>">
  <br>
  <label for="url">URL (Optional)</label>
  <input id="url" type="text" name="post[url]" value="<%= @post.url %>">

  <label for="content">Content (Optional) </label>
  <input id="content" type="text" name="post[content]" value="<%= @post.content %>">

  <label>Choose Subsploots</label>

  <input type="hidden" name="post[subreddit_ids][]" value="">

  <% Subreddit.all.each do |subreddit| %>
    <label><%= subreddit.title %>
      <input
        type="checkbox"
        value="<%= subreddit.id %>"
        name="post[subreddit_ids][]"
        <%#= "checked" if @post.subreddit_ids.include?(subreddit.id) %>
      />
    </label>
  <% end %>

  <input class="submit-button" type="submit" value="Edit Post">
</form>

W5D2/W5D2-projects/reddit_on_rails2/app/views/subreddits/edit.html.erb
<% unless flash.now[:errors].nil? %>
  <% flash.now[:errors].each do |error| %>
    <h1 class="error-text"><%= error %></h1>
  <% end %>
<% end %>

<h1>Subsploot Admin Panel</h1>

<form class="sign-in-form" action="<%= subreddit_url(@subreddit) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="title">Title</label>
  <input id="title" type="text" name="subreddit[title]" value="<%= @subreddit.title %>">
  <br>
  <label for="description">Description</label>
  <input id="description" type="text" name="subreddit[description]" value="<%= @subreddit.description %>">

  <input class="submit-button" type="submit" value="Update Subsploot">
</form>

W5D2/W5D2-projects/reddit_on_rails2/app/views/subreddits/index.html.erb
<br>
<img src="<%= random_corgi_url %>" alt="Corgi">
<br>
<%= link_to "Create Subsploot", new_subreddit_url, method: :get %>

<h1>Top Subsploots</h1>

<% @subreddits.each do |subreddit| %>
  <h3><%= subreddit.title %></h3>
  <%= link_to "View Subsploot", subreddit_url(subreddit), method: :get %>
  <%= button_to "Delete Subsploot", subreddit_url(subreddit), method: :delete%>
<% end %>

W5D2/W5D2-projects/reddit_on_rails2/app/views/subreddits/new.html.erb
<% unless flash.now[:errors].nil? %>
  <% flash.now[:errors].each do |error| %>
    <h1 class="error-text"><%= error %></h1>
  <% end %>
<% end %>

<h1>Create Subsploot</h1>

<form class="sign-in-form" action="<%= subreddits_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="title">Title</label>
  <input id="title" type="text" name="subreddit[title]" value="">
  <br>
  <label for="description">Description</label>
  <input id="description" type="text" name="subreddit[description]" value="">

  <% end %>

  <input class="submit-button" type="submit" value="Create Subsploot">
</form>

W5D2/W5D2-projects/reddit_on_rails2/app/views/subreddits/show.html.erb
<h1><%= @subreddit.title %></h1>
<p><%= @subreddit.description %></p>

<% unless flash.now[:errors].nil? %>
  <% flash.now[:errors].each do |error| %>
    <h1 class="error-text"><%= error %></h1>
  <% end %>
<% end %>

<% @subreddit.posts.each do |post| %>
  <h4><%= post.title %></h4>
  <h4><%= post.url %></h4>
  <h4><%= post.content %></h4>
  <% if post.author_id = current_user.id %>
    <%= link_to "Edit Post", edit_subreddit_post_url(@subreddit, post), method: :get %>
    <%= link_to "Delete Post", subreddit_post_url(@subreddit, post), method: :delete %>
  <% end %>
<% end %>

<h1>Make A Post</h1>

<form class="sign-in-form" action="<%= subreddit_posts_url(@subreddit) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="title">Title</label>
  <input id="title" type="text" name="post[title]" value="">
  <br>
  <label for="url">URL (Optional) </label>
  <input id="url" type="text" name="post[url]" value="">

  <label for="content">Content (Optional)</label>
  <input id="content" type="text" name="post[content]" value="">

  <br>
  <br>
  <label>Choose Subsploots</label>

  <input type="hidden" name="post[subreddit_ids][]">

  <% Subreddit.all.each do |subreddit| %>
    <br>
    <label>
      <input
        type="checkbox"
        value="<%= subreddit.id %>"
        name="post[subreddit_ids][]"
      /><%= subreddit.title %>
    </label>
  <% end %>
  <br>
  <input class="submit-button" type="submit" value="Make Post">
</form>

<%= link_to "Front Page", root_url, method: :get %>

<% if current_user.id == @subreddit.moderator_id %>
 <%= link_to "Subsploot Admin Panel", edit_subreddit_url(@subreddit), method: :get %>
<% end %>